In [1]:
import pandas as pd

In [13]:
df_titanic = pd.read_csv("../data/titanic.csv")
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
df_vacio = pd.DataFrame()
df_vacio

Empty DataFrame
Columns: []
Index: []

In [19]:
def describe_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Genera un resumen estadístico descriptivo de un DataFrame.

    Argumentos:
        df (pd.DataFrame): DataFrame a analizar.

    Retorna:
        pd.DataFrame: DataFrame con una fila por columna del input y las
        siguientes columnas: 'tipo', 'porcentaje_nulos', 'valores_unicos',
        'porcentaje_cardinalidad'.
        Retorna None si el input no es un DataFrame válido.
    """
    
    # Comprobación de que si es un DataFrame
    if not isinstance(df, pd.DataFrame):
        print("Error: el objeto proporcionado no es un DataFrame.")
        return None

    # Crear el DataFrame resultado
    resultado = pd.DataFrame(index=df.columns)

    # Tipo de dato
    resultado["tipo"] = df.dtypes.astype(str)

    # Porcentaje de nulos
    resultado["porcentaje_nulos"] = (df.isna().mean() * 100).round(2)

    # Valores únicos
    resultado["valores_unicos"] = df.nunique()

    # Porcentaje de cardinalidad
    resultado["porcentaje_cardinalidad"] = ((df.nunique() / len(df)) * 100).round(2)


    return resultado

In [20]:
describe_df(df_titanic["survived"])

Error: el objeto proporcionado no es un DataFrame.

In [21]:
describe_df(df_vacio)

Empty DataFrame
Columns: [tipo, porcentaje_nulos, valores_unicos, porcentaje_cardinalidad]
Index: []

In [22]:
describe_df(df_titanic)

,tipo,porcentaje_nulos,valores_unicos,porcentaje_cardinalidad
survived,int64,0.00,2,0.22
pclass,int64,0.00,3,0.34
sex,str,0.00,2,0.22
age,float64,19.87,88,9.88
sibsp,int64,0.00,7,0.79
parch,int64,0.00,7,0.79
fare,float64,0.00,248,27.83
embarked,str,0.22,3,0.34
class,str,0.00,3,0.34
who,str,0.00,3,0.34
adult_male,bool,0.00,2,0.22
deck,str,77.22,7,0.79
embark_town,str,0.22,3,0.34
alive,str,0.00,2,0.22
alone,bool,0.00,2,0.22

In [25]:
def tipifica_variables(df: pd.DataFrame, umbral_categorica: int, umbral_continua: float) -> pd.DataFrame:
    """
    Clasifica las variables de un DataFrame según su cardinalidad y porcentaje de cardinalidad.

    Argumentos:
        df (pd.DataFrame): DataFrame a analizar.
        umbral_categorica: Umbral para categorizar las variables categóricas
        umbral_continua: Float

    Retorna:
        pd.DataFrame: DataFrame con dos columnas: 'nombre_variable', 'tipo_sugerido'
        Retorna None si el input no es un DataFrame válido.
        Retorna None si el umbral_categorica no es un tipo válido (int).
        Retorna None si el umbral_continua no es un tipo válido (float)
    """
    
    # Comprobación de DataFrame
    if not isinstance(df, pd.DataFrame):
        print("Error: el objeto proporcionado no es un DataFrame.")
        return None
    
    # Comprobación umbral_categorica, debe ser entero positivo
    if not isinstance(umbral_categorica, int) or umbral_categorica <= 0:
        print("Error: umbral_categorica debe ser un entero positivo.")
        return None

    # comprobación umbral_continua, debe ser float entre 0 y 100
    if not isinstance(umbral_continua, float) or not (0 <= umbral_continua <= 100):
        print("Error: umbral_continua debe ser un float entre 0 y 100.")
        return None
    
    
    # Cardinalidad y porcentaje_cardinalidad
    cardinalidad = df.nunique()
    porcentaje_cardinalidad = df.nunique() / len(df) * 100

    # Clasificación variables
    tipos = []

    for col in df.columns:
        card = cardinalidad[col]
        pct = porcentaje_cardinalidad[col]

        if card == 2:
            tipo = "Binaria"

        elif card < umbral_categorica:
            tipo = "Categórica"

        elif card >= umbral_categorica and pct >= umbral_continua:
            tipo = "Numérica Continua"

        else:
            tipo = "Numérica Discreta"

        tipos.append(tipo)
    
    # DF resultado
    resultado = pd.DataFrame({
        "nombre_variable": df.columns,
        "tipo_sugerido": tipos
    })

    return resultado

In [28]:
tipifica_variables(df_titanic, umbral_categorica=10, umbral_continua=5.0)

   nombre_variable      tipo_sugerido
0         survived            Binaria
1           pclass         Categórica
2              sex            Binaria
3              age  Numérica Continua
4            sibsp         Categórica
5            parch         Categórica
6             fare  Numérica Continua
7         embarked         Categórica
8            class         Categórica
9              who         Categórica
10      adult_male            Binaria
11            deck         Categórica
12     embark_town         Categórica
13           alive            Binaria
14           alone            Binaria

In [29]:
tipifica_variables(df_titanic["who"], umbral_categorica=10, umbral_continua=5.0)

Error: el objeto proporcionado no es un DataFrame.

In [31]:
tipifica_variables(df_titanic, umbral_categorica=-10.2, umbral_continua=5.0)

Error: umbral_categorica debe ser un entero positivo.

In [32]:
tipifica_variables(df_titanic, umbral_categorica=10, umbral_continua=-2.0)

Error: umbral_continua debe ser un float entre 0 y 100.

In [33]:
tipifica_variables(df_vacio, umbral_categorica=10, umbral_continua=5.0)

Empty DataFrame
Columns: [nombre_variable, tipo_sugerido]
Index: []